name: Update CHANGELOG on version bum

on:
  pull_request:
    paths:
      - config.yaml
    types:
      - opened
      - synchronize

jobs:
  update-changelog:
    if: github.actor == 'renovate[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract new version from config.yaml
        id: extract
        run: |
          NEW_VERSION=$(grep 'version:' config.yaml | sed -E 's/version: "?([0-9\.]+)"?/\1/')
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Get release info from GitHub
        id: release
        run: |
          VERSION=${{ steps.extract.outputs.version }}
          RELEASE_INFO=$(curl -s https://api.github.com/repos/wppconnect-team/wppconnect-server/releases/tags/v$VERSION)
          BODY=$(echo "$RELEASE_INFO" | jq -r .body)
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Prepend to CHANGELOG.md
        run: |
          VERSION=${{ steps.extract.outputs.version }}
          DATE=$(date +%Y-%m-%d)
          echo -e "## [${VERSION}] - ${DATE}\n${{ steps.release.outputs.body }}\n\n$(cat CHANGELOG.md)" > CHANGELOG.md

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update CHANGELOG for version ${{ steps.extract.outputs.version }}"
          branch: ${{ github.head_ref }}
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          push_options: --force
        env:
          GIT_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
