name: Update Add-on Version

on:
  schedule:
    - cron: "0 6 * * *" # Executa diariamente às 6h UTC
  workflow_dispatch:

jobs:
  update-addon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Obter o digest da imagem mais recente
        id: image
        run: |
          DIGEST=$(docker pull server-cli:latest | grep "Digest:" | awk '{print $2}')
          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT

      - name: Verificar se o digest já está no repositório
        id: check
        run: |
          if git grep -q "${{ steps.image.outputs.digest }}"; then
            echo "imagem_atualizada=true" >> $GITHUB_OUTPUT
          else
            echo "imagem_atualizada=false" >> $GITHUB_OUTPUT
          fi

      - name: Atualizar versão no config.yaml
        if: steps.check.outputs.imagem_atualizada == 'false'
        run: |
          NOVA_VERSAO=$(date +'%Y.%m.%d.%H%M')
          sed -i "s/^version: .*/version: \"${NOVA_VERSAO}\"/" config.yaml
          echo "digest: ${{ steps.image.outputs.digest }}" >> config.yaml

      - name: Commit e push das alterações
        if: steps.check.outputs.imagem_atualizada == 'false'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add config.yaml
          git commit -m "Atualizar para imagem mais recente"
          git push
